<?php
$product = $block->getProduct();
if (!$product->getIsSalable() || $product->isVirtual()) {
    return false;
}

?>
<div class="clawrock-productshipping"
     data-mage-init='{"ClawRock_ProductShipping/js/shipping-methods": {
        "url": "<?php echo $block->escapeHtml($block->getShippingMethodsUrl()); ?>",
        "sku": "<?php echo $block->escapeHtml($product->getSku()); ?>",
        "type": "<?php echo $block->escapeHtml($product->getTypeId()); ?>",
        "message": "<?php echo $block->escapeHtml($block->getCustomMessage()); ?>"
    }, "loader": {
        "icon": "<?php echo /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>",
        "texts": {}
    }}'>
    <h3>Shipping methods:</h3>
    <div id="clawrock-shipping-methods">
        <ul>

        </ul>
    </div>
</div>
<script id="shipping-methods-template" type="text/x-magento-template">
    <li>
        <%- data.title %>: <span><%- data.price %></span>
    </li>
</script>
